
services:

  db:
    name: afinitly-auth-service-users-dev-db
    image: postgres
    restart: until-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: users-dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: until-stopped
    ports:
      - 8080:8080
